name: Rename l10n files

on:
  pull_request:
    branches: [ rename_test ]
    types: [opened, synchronize]

jobs:
  rename_files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Rename files
      run: |
        while read oldrev newrev refname
        do
          if [ "$refname" = "refs/heads/${{ github.head_ref }}" ]; then
            git ls-tree --name-only -r $newrev | grep -E ".*\.en\..*\..*" > /dev/null
            if [ $? -eq 0 ]; then
              echo "File(s) detected in push. Renaming..."
              git checkout $newrev
              for f in $(find -type f -iwholename "*/*.en.??.*"); do
                filename=$(basename -- "$f" | sed 's/\.en\..*\..*$//')
                tlc=$(echo $f | sed 's/^.*\.en\.\([^.]*\)\..*$/\1/')
                ext=$(echo $f | sed 's/^.*\.\([^.]*\)$/\1/')
                dirname=$(dirname -- "$f")
                #git mv $f "${dirname}/${filename}.${tlc}.${ext}"
                echo "Would rename $f to ${dirname}/${filename}.${tlc}.${ext}"
              done
              #git add .
              #GIT_COMMITTER_DATE="$(date -R)" git commit --amend --no-edit --no-post-rewrite
              echo "Files renamed."
              #git push -f
            fi
          fi
        done
      env:
        GIT_COMMITTER_NAME: Your Name
        GIT_COMMITTER_EMAIL: your.email@example.com
