name: Rename l10n files

on:
  push:
    branches: [ l10n_test ]

jobs:
  rename_l10n_files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Rename l10n files
      run: |
            renames=$(find -type f -iwholename "*/*.en.??.*")
            if [ -n "$renames" ]; then
              git config --global user.name "github-actions"
              git config --global user.email "github-actions[bot]@users.noreply.github.com"
              for f in $renames; do
                filename=$(basename -- "$f" | sed 's/\.en\..*\..*$//')
                tlc=$(echo $f | sed 's/^.*\.en\.\([^.]*\)\..*$/\1/')
                ext=$(echo $f | sed 's/^.*\.\([^.]*\)$/\1/')
                dirname=$(dirname -- "$f")
                git mv -v $f "${dirname}/${filename}.${tlc}.${ext}"
              done
              git status --porcelain | grep -E "^R"
              if [ $? -eq 0 ]; then
                git add --all
                GIT_COMMITTER_DATE="$(date -R)" git commit -v -m "chore(l10n): Rename l10n files"
                git push
              else
                echo "Nothing to commit, working tree clean"
              fi
            else
              echo "No file to rename"
            fi
